theme = "trans_theme"
# theme = "ashokai_urple"


[keys.normal]
"X" = "extend_line_above"


[keys.normal.space.z]
"z" = "rotate_view"
"v" = "vsplit"
"s" = "hsplit"
"up" = "jump_view_up"
"down" = "jump_view_down"
"right" = "jump_view_right"
"left" = "jump_view_left"


[keys.normal.g]
"g" = "goto_word"
"G" = "goto_file_start"

[keys.select.g]
"g" = "goto_word"
"G" = "goto_file_start"


[keys.insert]
"j" = { "j" = "normal_mode" }


[editor]
line-number = "relative"
bufferline = "never" # always, never, multiple
true-color = true
end-of-line-diagnostics = "error"
popup-border = "all"
trim-trailing-whitespace = true
# rainbow-brackets = true
preview-completion-insert = false


[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.cursor-shape]
normal = "block" # block, bar, underline, hidden
insert = "bar"
select = "underline"


[editor.statusline]
left = ["mode", "file-name", "spinner"]
center = ["position", "separator", "total-line-numbers", "spacer", "diagnostics"]
right = ["position-percentage", "file-type", "separator", "selections", "file-encoding"]
separator = "|"
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"


[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'


[editor.whitespace.render]
space = "none"
# tab = "all"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
# tab = "→"
# newline = "⏎"
# tabpad = "·"


[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
